controllers:
  - displayName: Controller Production
    controllerHost: https://xxxx.saas.appdynamics.com
    createDashboard: true
    userName: e-mail@acme.com
    password: mypassowrd
    accountName: xxxx
    proxyHost:
    proxyPort:
    proxySsl:

numberOfThreads: 30
metricPrefix: Custom Metrics|CSA-License|
encryptionKey:
formatDate: dd/MM/yyyy HH:mm:ss
frequency: 30
